# Site settings
title: AlanCoding (github) homepage
email: alan.rominger@gmail.com

description: > # this means to ignore newlines until "baseurl:"
  This is my personal Jekyll static files base.

# More things which are YAML-y
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://alancoding.github.io" # the base hostname & protocol for your site
twitter_username: AlanRominger
github_username:  AlanCoding

# Build settings
markdown: kramdown
